### ISSUE TITLE
Humidity not displaying

### ISSUE THREAD

**Issue by kevschuetz** [saabman/MMM-WunderGround-PWS-Observations#2]
Hello Saabman!

First of all thank you for reviving the Wunderground module, it is really great!!

I have a simple Sense Hat for my Raspberry Pi which is possible of catching temperature, pressure and humidity. I configured those with the value 1 in the config.js but somehow the humidity is not showing (no icon and no value). 
Checked on wunderground and the humidity data is there, so i just wanted to know if this is a known issue (as i could not find humidity data on your screenshots) or if this is a problem on my side.

Thanks in advance!

**Comment by saabman** [comment]
Hi kevschuetz,

Thanks for pointing that out, damn spelling errors 🤣 
should be right now.
 
do a git pull and it should just work

**Comment by kevschuetz** [comment]
Thank you, works perfectly now!
